version: '3'
services:
    web-magento1-phpunit:
        image: webdevops/php-apache-dev:5.6
        container_name: web-magento1-phpunit
        restart: always
        environment:
          - WEB_ALIAS_DOMAIN=magento1-phpunit.local
          - WEB_DOCUMENT_ROOT=/app
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - /path/to/magento:/app:delegated
        links:
          - mysql-magento1-phpunit
    mysql-magento1-phpunit:
        image: mariadb:10
        container_name: mysql-magento1-phpunit
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento_tests
        volumes:
          - db-data-magento1-phpunit:/var/lib/mysql:delegated

volumes:
    db-data-magento1-phpunit:
        external: false
