#!/bin/bash
# Run the tests with PHPunit inside the container. An optional filter parameter
# can be passed additionally, in order to execute specific classes / tests only.

scriptDir="$(dirname $(readlink $0))"
magentoDir="$scriptDir/magento"
modmanDir="$magentoDir/.modman"
callingDir="$PWD"
callingDirName="${PWD##*/}"

cleanup() {
    cd $magentoDir
    if [ ! -z "$(modman list)" ]; then
        echo "Removing installed modules..."
        for module in $(modman list); do
            modman remove $module
        done
    fi
}

dockerExec() {
    docker exec -it web-magento1-phpunit bash -c "$1"
}

trap cleanup EXIT

if [[ $(docker ps | grep phpunit | wc -l) -lt 2 ]]; then
    echo "Starting the PHPUnit container..."
    cd $scriptDir && docker-compose up -d --build
fi

if [[ -f modman ]]; then
    cp -R $callingDir $modmanDir/.
    cd $modmanDir
    modman deploy $callingDirName
else
    echo "Warning: no modman file found in the current directory."
fi

filter="$1"

cd $scriptDir
# Run all tests or only specific classes / tests.
if [ -z $filter ]; then
    echo "Running the test suite..."
    dockerExec "cd app && ./vendor/bin/phpunit"
else
    echo "Running the test suite for ${filter}..."
    dockerExec "cd app && ./vendor/bin/phpunit --filter $filter"
fi
